// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: im.proto

package imclient

import (
	"context"

	"github.com/peter6866/SimpleChatter/apps/im/rpc/im"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatLog                     = im.ChatLog
	Conversation                = im.Conversation
	CreateGroupConversationReq  = im.CreateGroupConversationReq
	CreateGroupConversationResp = im.CreateGroupConversationResp
	GetChatLogReq               = im.GetChatLogReq
	GetChatLogResp              = im.GetChatLogResp
	GetConversationsReq         = im.GetConversationsReq
	GetConversationsResp        = im.GetConversationsResp
	PutConversationsReq         = im.PutConversationsReq
	PutConversationsResp        = im.PutConversationsResp
	SetUpUserConversationReq    = im.SetUpUserConversationReq
	SetUpUserConversationResp   = im.SetUpUserConversationResp

	Im interface {
		// Get Chat log
		GetChatLog(ctx context.Context, in *GetChatLogReq, opts ...grpc.CallOption) (*GetChatLogResp, error)
		// Setup conversation (DM, Group)
		SetUpUserConversation(ctx context.Context, in *SetUpUserConversationReq, opts ...grpc.CallOption) (*SetUpUserConversationResp, error)
		// Get Conversations
		GetConversations(ctx context.Context, in *GetConversationsReq, opts ...grpc.CallOption) (*GetConversationsResp, error)
		// Put Conversations
		PutConversations(ctx context.Context, in *PutConversationsReq, opts ...grpc.CallOption) (*PutConversationsResp, error)
		CreateGroupConversation(ctx context.Context, in *CreateGroupConversationReq, opts ...grpc.CallOption) (*CreateGroupConversationResp, error)
	}

	defaultIm struct {
		cli zrpc.Client
	}
)

func NewIm(cli zrpc.Client) Im {
	return &defaultIm{
		cli: cli,
	}
}

// Get Chat log
func (m *defaultIm) GetChatLog(ctx context.Context, in *GetChatLogReq, opts ...grpc.CallOption) (*GetChatLogResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.GetChatLog(ctx, in, opts...)
}

// Setup conversation (DM, Group)
func (m *defaultIm) SetUpUserConversation(ctx context.Context, in *SetUpUserConversationReq, opts ...grpc.CallOption) (*SetUpUserConversationResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.SetUpUserConversation(ctx, in, opts...)
}

// Get Conversations
func (m *defaultIm) GetConversations(ctx context.Context, in *GetConversationsReq, opts ...grpc.CallOption) (*GetConversationsResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.GetConversations(ctx, in, opts...)
}

// Put Conversations
func (m *defaultIm) PutConversations(ctx context.Context, in *PutConversationsReq, opts ...grpc.CallOption) (*PutConversationsResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.PutConversations(ctx, in, opts...)
}

func (m *defaultIm) CreateGroupConversation(ctx context.Context, in *CreateGroupConversationReq, opts ...grpc.CallOption) (*CreateGroupConversationResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.CreateGroupConversation(ctx, in, opts...)
}
