// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	friend "github.com/peter6866/SimpleChatter/apps/social/api/internal/handler/friend"
	group "github.com/peter6866/SimpleChatter/apps/social/api/internal/handler/group"
	"github.com/peter6866/SimpleChatter/apps/social/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Friend Request
				Method:  http.MethodPost,
				Path:    "/friend/putIn",
				Handler: friend.FriendPutInHandler(serverCtx),
			},
			{
				// Handle friend request
				Method:  http.MethodPut,
				Path:    "/friend/putIn",
				Handler: friend.FriendPutInHandleHandler(serverCtx),
			},
			{
				// Friend request list
				Method:  http.MethodGet,
				Path:    "/friend/putIns",
				Handler: friend.FriendPutInListHandler(serverCtx),
			},
			{
				// Friend list
				Method:  http.MethodGet,
				Path:    "/friends",
				Handler: friend.FriendListHandler(serverCtx),
			},
			{
				// friends online
				Method:  http.MethodGet,
				Path:    "/friends/online",
				Handler: friend.FriendsOnlineHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/social"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// create group
				Method:  http.MethodPost,
				Path:    "/group",
				Handler: group.CreateGroupHandler(serverCtx),
			},
			{
				// apply to join group
				Method:  http.MethodPost,
				Path:    "/group/putIn",
				Handler: group.GroupPutInHandler(serverCtx),
			},
			{
				// handle apply to join group
				Method:  http.MethodPut,
				Path:    "/group/putIn",
				Handler: group.GroupPutInHandleHandler(serverCtx),
			},
			{
				// apply to join group list
				Method:  http.MethodGet,
				Path:    "/group/putIns",
				Handler: group.GroupPutInListHandler(serverCtx),
			},
			{
				// group user list
				Method:  http.MethodGet,
				Path:    "/group/users",
				Handler: group.GroupUserListHandler(serverCtx),
			},
			{
				// group user online
				Method:  http.MethodGet,
				Path:    "/group/users/online",
				Handler: group.GroupUserOnlineHandler(serverCtx),
			},
			{
				// user group list
				Method:  http.MethodGet,
				Path:    "/groups",
				Handler: group.GroupListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/social"),
	)
}
